### ISSUE TITLE
Run xesmf on MUR SST

### ISSUE THREAD

**Issue by maxrjones** [developmentseed/warp-resample-profiling#10]
This is blocked by https://github.com/conda-forge/esmf-feedstock/pull/123 due to https://github.com/pangeo-data/xESMF/issues/380. After the conda-forge release, I will:
 - [ ] Update the docker image to include the latest results
 - [ ] Generate weights
 - [ ] Rerun the examples including xesmf

**Comment by maxrjones** [comment]
Generating the weights using XESMF was prohibitively slow on MUR SST (I killed the workflow after 2 hours on a 128 GB RAM machine). Parallel weight generation did not help. I think it would be necessary to use the ESMF_Regrid command with mpirun (xref https://discourse.pangeo.io/t/upsample-and-regrid-curvilinear-grid-of-geostationary-data/2137/15), which is out of the scope of this guidebook. I'm closing this as not planned.

**Comment by mdsumner** [comment]
Can you share the setup details though?

**Comment by maxrjones** [comment]
In terms of code, I was running https://developmentseed.org/warp-resample-profiling/examples/generate-weights.html using `dataset="mursst"` at the last cells.

In terms of computational setup, I was using the Docker image `quay.io/developmentseed/warp-resample-profiling:latest` on an AWS EC2 instances with ~16 CPUs and ~128 GB RAM.

**Comment by mdsumner** [comment]
Thank you!
